name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: jitterbit/get-changed-files@v1
      - id: files
      - name: Get All Changed Files
      - run: |
          for changed_file in ${{ steps.files.outputs.added_modified }}; do
            echo "Do something with this ${changed_file}."
          done

#curl --location --request PUT 'https://t1h8ftxrq4.execute-api.eu-west-2.amazonaws.com/default/validator-prod' \
#--header 'Content-Type: text/plain' \
#--data-raw
