name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: jitterbit/get-changed-files@v1
        id: files
      - name: Changed files
        run: |
          echo "All:"
          echo "${{ steps.files.outputs.all }}"
          for changed_file in ${{ steps.files.outputs.added_modified }}; do
            echo "Do something with this ${changed_file}."
          done
